version: '3'

services:
  db:
    image: postgres:15-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '40000:5432'
    environment:
      POSTGRES_USER: 'albert'
      POSTGRES_DB: 'albert'
      POSTGRES_PASSWORD: 'secret'
  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - db
    ports:
      - '8080:8080'

volumes:
  postgres_data:
    driver: local


